-- On-demand snapshots. No automatic freshness claim.
USE DATABASE IDENTIFIER($DEMO_DB);
USE SCHEMA CURATED;
USE WAREHOUSE IDENTIFIER($DEMO_WH);

CREATE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT portfolio.ID AS ENTITY_ID, portfolio.NAME AS ENTITY_NAME,
       portfolio.REGION, portfolio.CATEGORY, portfolio.RISK_TIER, portfolio.STATUS,
       COUNT(*) AS EVENT_COUNT,
       SUM(observation.CONTRACT_COUNT) AS CONTRACT_COUNT,
       SUM(observation.VALUE_MYR) AS VALUE_MYR,
       SUM(observation.EXCEPTION_COUNT) AS EXCEPTION_COUNT,
       SUM(observation.ESCALATED_COUNT) AS ESCALATED_COUNT,
       SUM(observation.SLA_BREACHED) AS SLA_BREACH_COUNT,
       SUM(observation.REVIEW_DUE) AS REVIEW_DUE,
       SUM(observation.REVIEW_COMPLETED) AS REVIEW_COMPLETED,
       100.0 * (SUM(observation.CONTRACT_COUNT) - SUM(observation.EXCEPTION_COUNT)) / NULLIF(SUM(observation.CONTRACT_COUNT), 0) AS CLEAN_RATE_PCT,
       100.0 * SUM(observation.ESCALATED_COUNT) / NULLIF(SUM(observation.EXCEPTION_COUNT), 0) AS ESCALATION_SHARE_PCT,
       100.0 * SUM(observation.REVIEW_COMPLETED) / NULLIF(SUM(observation.REVIEW_DUE), 0) AS REVIEW_COMPLIANCE_PCT,
       AVG(observation.DOC_REJECT_PCT) AS AVG_DOC_REJECT_PCT,
       MAX(observation.EVENT_DATE) AS SOURCE_WATERMARK
FROM RAW.PORTFOLIO_DAILY observation
JOIN RAW.PORTFOLIOS portfolio ON portfolio.ID = observation.ENTITY_ID
GROUP BY portfolio.ID, portfolio.NAME, portfolio.REGION, portfolio.CATEGORY, portfolio.RISK_TIER, portfolio.STATUS;

CREATE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT EVENT_DATE AS METRIC_DATE, COUNT(*) AS EVENT_COUNT,
       SUM(CONTRACT_COUNT) AS CONTRACT_COUNT, SUM(VALUE_MYR) AS VALUE_MYR,
       SUM(EXCEPTION_COUNT) AS EXCEPTION_COUNT, SUM(ESCALATED_COUNT) AS ESCALATED_COUNT,
       100.0 * SUM(ESCALATED_COUNT) / NULLIF(SUM(EXCEPTION_COUNT), 0) AS ESCALATION_SHARE_PCT
FROM RAW.PORTFOLIO_DAILY
GROUP BY EVENT_DATE;

CREATE DYNAMIC TABLE CURATED.EXCEPTION_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT EXCEPTION_REASON, SUM(EXCEPTION_COUNT) AS EXCEPTION_COUNT,
       SUM(ESCALATED_COUNT) AS ESCALATED_COUNT,
       SUM(SLA_BREACHED) AS SLA_BREACH_COUNT,
       SUM(VALUE_MYR) AS EXPOSED_VALUE_MYR,
       100.0 * SUM(ESCALATED_COUNT) / NULLIF(SUM(EXCEPTION_COUNT), 0) AS ESCALATION_SHARE_PCT
FROM RAW.PORTFOLIO_DAILY
WHERE EXCEPTION_COUNT > 0
GROUP BY EXCEPTION_REASON;

CREATE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = DOWNSTREAM WAREHOUSE = __DEMO_WH__
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH observations AS (
  SELECT SUM(CONTRACT_COUNT) AS CONTRACTS, SUM(EXCEPTION_COUNT) AS EXCEPTIONS,
         SUM(ESCALATED_COUNT) AS ESCALATED, SUM(SLA_BREACHED) AS BREACHES, SUM(VALUE_MYR) AS VALUE_MYR,
         SUM(REVIEW_DUE) AS REVIEW_DUE, SUM(REVIEW_COMPLETED) AS REVIEW_COMPLETED,
         MAX(EVENT_DATE) AS SOURCE_WATERMARK
  FROM RAW.PORTFOLIO_DAILY
), book AS (SELECT COUNT(*) AS PORTFOLIO_COUNT FROM RAW.PORTFOLIOS),
documents AS (
  SELECT 100.0 * SUM(LEAST(ON_FILE_QTY, REQUIRED_QTY)) / NULLIF(SUM(REQUIRED_QTY), 0) AS COVERAGE_PCT,
         SUM(PENDING_QTY) AS PENDING
  FROM RAW.CONTRACT_DOCUMENTS
), metrics AS (
  SELECT 1 AS SORT_ORDER, 'Clean Review Rate' AS TITLE,
         100.0 * (CONTRACTS - EXCEPTIONS) / NULLIF(CONTRACTS, 0) AS VALUE_NUM, '%' AS UNIT FROM observations
  UNION ALL SELECT 2, 'Documentation Exceptions', EXCEPTIONS, '' FROM observations
  UNION ALL SELECT 3, 'Escalated to Shariah Committee', ESCALATED, '' FROM observations
  UNION ALL SELECT 4, 'Escalation Rate', 100.0 * ESCALATED / NULLIF(EXCEPTIONS, 0), '%' FROM observations
  UNION ALL SELECT 5, 'Rectification SLA Breaches', BREACHES, '' FROM observations
  UNION ALL SELECT 6, 'Reviewed Value (MYR M)', VALUE_MYR / 1e6, '' FROM observations
  UNION ALL SELECT 7, 'Contracts Reviewed', CONTRACTS, '' FROM observations
  UNION ALL SELECT 8, 'Process Review Compliance', 100.0 * REVIEW_COMPLETED / NULLIF(REVIEW_DUE, 0), '%' FROM observations
  UNION ALL SELECT 9, 'Portfolios Monitored', PORTFOLIO_COUNT, '' FROM book
  UNION ALL SELECT 10, 'Contract File Coverage', COVERAGE_PCT, '%' FROM documents
  UNION ALL SELECT 11, 'Contract Documents Pending', PENDING, '' FROM documents
)
SELECT metrics.SORT_ORDER, metrics.TITLE, metrics.VALUE_NUM,
       IFF(metrics.VALUE_NUM IS NULL, 'Unavailable',
           CASE WHEN metrics.UNIT = '' THEN TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM), '999,999,999,990'))
                WHEN metrics.SORT_ORDER = 1 THEN TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM, 2), '990.00'))
                ELSE TRIM(TO_VARCHAR(ROUND(metrics.VALUE_NUM, 1), '990.0')) END || metrics.UNIT) AS DISPLAY,
       'neutral' AS STATUS, observations.SOURCE_WATERMARK
FROM metrics CROSS JOIN observations;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.EXCEPTION_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
