-- Generated from generator/demo_specs/aws-malaysia-islamic-finance-shariah.json
-- Regenerate with: python3 generator/gen_repo_docs.py aws-malaysia-islamic-finance-shariah
-- This is the schema that is actually deployed for MY_ISLAMIC_FINANCE_SHARIAH.

-- Alerts fire on the bottom tail of SAC Resolutions
-- (lower is worse for this metric).
CREATE OR REPLACE DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
WITH thresh AS (
  SELECT PERCENTILE_CONT(0.09) WITHIN GROUP (ORDER BY KPI_SAC_RESOLUTIONS) AS T
  FROM RAW.COMPLIANCE_EVENTS
)
SELECT
  e.ID AS ENTITY_ID,
  e.NAME AS ENTITY_NAME,
  e.REGION,
  e.CATEGORY,
  e.STATUS,
  COUNT(*) AS EVENT_COUNT,
  SUM(CASE WHEN f.KPI_SAC_RESOLUTIONS <= (SELECT T FROM thresh) THEN 1 ELSE 0 END) AS ALERT_COUNT,
  ROUND(AVG(f.KPI_SAC_RESOLUTIONS), 2) AS AVG_SAC_RESOLUTIONS,
  ROUND(AVG(f.KPI_NEW_RULINGS), 2) AS AVG_NEW_RULINGS,
  ROUND(AVG(f.KPI_COMPLIANCE_RATE), 2) AS AVG_COMPLIANCE_RATE
FROM RAW.COMPLIANCE_EVENTS f
JOIN RAW.BNM_GUIDELINES e ON e.ID = f.ENTITY_ID
CROSS JOIN thresh
GROUP BY e.ID, e.NAME, e.REGION, e.CATEGORY, e.STATUS;

CREATE OR REPLACE DYNAMIC TABLE CURATED.TREND_ANALYSIS
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS
SELECT
  f.EVENT_DATE AS METRIC_DATE,
  COUNT(*) AS EVENT_COUNT,
  ROUND(AVG(f.KPI_SAC_RESOLUTIONS), 2) AS AVG_SAC_RESOLUTIONS,
  ROUND(AVG(f.KPI_NEW_RULINGS), 2) AS AVG_NEW_RULINGS,
  ROUND(AVG(f.KPI_COMPLIANCE_RATE), 2) AS AVG_COMPLIANCE_RATE
FROM RAW.COMPLIANCE_EVENTS f
GROUP BY f.EVENT_DATE;

-- DISPLAY is rendered here so it is byte-identical to the card the app
-- was designed with (asserted by the round-trip check in kpi_parse.py).
CREATE OR REPLACE DYNAMIC TABLE CURATED.KPI_SUMMARY
  TARGET_LAG = '30 days' WAREHOUSE = TOURISM_WH
  REFRESH_MODE = FULL INITIALIZE = ON_CREATE
AS WITH ev AS (SELECT AVG(KPI_SAC_RESOLUTIONS) AS KPI_SAC_RESOLUTIONS, AVG(KPI_COMPLIANCE_RATE) AS KPI_COMPLIANCE_RATE, AVG(KPI_NEW_RULINGS) AS KPI_NEW_RULINGS FROM RAW.COMPLIANCE_EVENTS),
     en AS (SELECT SUM(KPI_SHARIAH_AUM) AS KPI_SHARIAH_AUM, SUM(KPI_PRODUCTS_SCREENED) AS KPI_PRODUCTS_SCREENED, SUM(KPI_EQUITIES_SCREENED) AS KPI_EQUITIES_SCREENED, SUM(KPI_SUKUK_REVIEWED) AS KPI_SUKUK_REVIEWED FROM RAW.BNM_GUIDELINES)
  SELECT 1 AS SORT_ORDER, 'Shariah AUM' AS TITLE, KPI_SHARIAH_AUM AS VALUE_NUM, 'RM' || ' ' || TO_VARCHAR(CAST(ROUND(((KPI_SHARIAH_AUM) / 1000000000)) AS DECIMAL(38,0))) || 'B' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 2 AS SORT_ORDER, 'SAC Resolutions' AS TITLE, KPI_SAC_RESOLUTIONS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_SAC_RESOLUTIONS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 3 AS SORT_ORDER, 'Products Screened' AS TITLE, KPI_PRODUCTS_SCREENED AS VALUE_NUM, LTRIM(TO_VARCHAR(CAST(ROUND((KPI_PRODUCTS_SCREENED)) AS DECIMAL(38,0)), '999,999,999,999')) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 4 AS SORT_ORDER, 'Compliance Rate' AS TITLE, KPI_COMPLIANCE_RATE AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_COMPLIANCE_RATE)) AS DECIMAL(38,0))) || '%' AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 5 AS SORT_ORDER, 'Equities Screened' AS TITLE, KPI_EQUITIES_SCREENED AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_EQUITIES_SCREENED)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 6 AS SORT_ORDER, 'Sukuk Reviewed' AS TITLE, KPI_SUKUK_REVIEWED AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_SUKUK_REVIEWED)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en
UNION ALL
  SELECT 7 AS SORT_ORDER, 'New Rulings' AS TITLE, KPI_NEW_RULINGS AS VALUE_NUM, TO_VARCHAR(CAST(ROUND((KPI_NEW_RULINGS)) AS DECIMAL(38,0))) AS DISPLAY, 'neutral' AS STATUS FROM ev CROSS JOIN en;

ALTER DYNAMIC TABLE CURATED.PERFORMANCE_SUMMARY SUSPEND;
ALTER DYNAMIC TABLE CURATED.TREND_ANALYSIS SUSPEND;
ALTER DYNAMIC TABLE CURATED.KPI_SUMMARY SUSPEND;
