-- ============================================================================
-- 99_RESET.SQL — Reset Shariah Compliance Monitoring to clean demo state
-- ============================================================================
USE DATABASE ISLAMIC_SHARIAH_COMPLIANCE;

-- Suspend tasks during demo
ALTER TASK IF EXISTS APP.TASK_PARSE_CONTRACTS SUSPEND;
ALTER TASK IF EXISTS APP.TASK_VALIDATE_COMPLIANCE SUSPEND;
ALTER TASK IF EXISTS APP.TASK_REFRESH_SEARCH SUSPEND;

-- Force refresh Dynamic Tables
ALTER DYNAMIC TABLE CURATED.CONTRACT_COMPLIANCE_STATUS REFRESH;
ALTER DYNAMIC TABLE CURATED.FATWA_CONFLICT_MATRIX REFRESH;
ALTER DYNAMIC TABLE CURATED.COMPLIANCE_DASHBOARD REFRESH;
ALTER DYNAMIC TABLE CURATED.AUDIT_TIMELINE REFRESH;

-- Verify key demo numbers
-- SELECT COUNT(*) FROM ISLAMIC_SHARIAH_COMPLIANCE.RAW.FINANCING_CONTRACTS → 5000
-- SELECT COUNT(*) FROM ISLAMIC_SHARIAH_COMPLIANCE.RAW.FATWA_LIBRARY → 200
-- SELECT COUNT(*) FROM ISLAMIC_SHARIAH_COMPLIANCE.RAW.COMPLIANCE_EVENTS → 8000

-- Resume tasks
ALTER TASK IF EXISTS APP.TASK_REFRESH_SEARCH RESUME;
ALTER TASK IF EXISTS APP.TASK_VALIDATE_COMPLIANCE RESUME;
ALTER TASK IF EXISTS APP.TASK_PARSE_CONTRACTS RESUME;
